TFJ-373 java.lang.NoSuchMethodError in twitter4j.internal.logging.Log4JLogger previous commit causes NoClassDefFoundError in twitter4j.internal.logging.Logger