TFJ-564 the JSONTokener embedded in Android platform doesn't have a constructor that takes Reader. http://developer.android.com/reference/org/json/JSONTokener.html With this fix, android version of Twitter4J doesn't use JSONTokener to workaround NoSuchMethodError.